INFO:[1]: Certifying 'n9n20182l_flat.fits' 
ERROR[1]: Validation failed for '/grp/hst/cdbs/lref/n9n20182l_flat.fits' : Missing required keyword 'VCALCOS' 
INFO:[2]: Certifying 'r7p1113nl_geo.fits' 
INFO:[3]: Certifying 's7g17006l_1dx.fits' 
INFO:[4]: Certifying 's7g17007l_1dx.fits' 
INFO:[5]: Certifying 's7g1700cl_geo.fits' 
INFO:[6]: Certifying 's7g1700dl_bpix.fits' 
INFO:[7]: Certifying 's7g1700el_brf.fits' 
INFO:[8]: Certifying 's7g1700fl_burst.fits' 
INFO:[9]: Certifying 's7g1700gl_dead.fits' 
INFO:[10]: Certifying 's7g1700il_lamp.fits' 
INFO:[11]: Certifying 's7g1700jl_pha.fits' 
INFO:[12]: Certifying 's7g1700kl_phot.fits' 
INFO:[13]: Certifying 's7g1700nl_1dx.fits' 
INFO:[14]: Certifying 's7g1700ol_1dx.fits' 
INFO:[15]: Certifying 's7g1700pl_bpix.fits' 
INFO:[16]: Certifying 's7g1700ql_dead.fits' 
INFO:[17]: Certifying 's7g1700tl_flat.fits' 
INFO:[18]: Certifying 's7g17010l_lamp.fits' 
INFO:[19]: Certifying 's7g17011l_phot.fits' 
INFO:[20]: Certifying 's7g17013l_disp.fits' 
INFO:[21]: Certifying 's7o1739kl_badt.fits' 
INFO:[22]: Certifying 't2314311l_wcp.fits' 
INFO:[23]: Certifying 't2314312l_tds.fits' 
ERROR[2]: Validation failed for '/grp/hst/cdbs/lref/t2314312l_tds.fits' : [Errno 2] No such file or directory: '/Users/jmiller/work/normal/lib/python2.7/site-packages/crds/hst/cdbs/cdbs_tpns/cos_tds.tpn' 
INFO:[24]: Certifying 't2314313l_wcp.fits' 
INFO:[25]: Certifying 't2314314l_tds.fits' 
ERROR[3]: Validation failed for '/grp/hst/cdbs/lref/t2314314l_tds.fits' : [Errno 2] No such file or directory: '/Users/jmiller/work/normal/lib/python2.7/site-packages/crds/hst/cdbs/cdbs_tpns/cos_tds.tpn' 
INFO:[26]: Certifying 't2k1224el_disp.fits' 
INFO:[27]: Certifying 't9b18112l_wcp.fits' 
INFO:[28]: Certifying 't9e1307kl_disp.fits' 
INFO:[29]: Certifying 't9e1307ll_disp.fits' 
INFO:[30]: Certifying 't9h1220sl_phot.fits' 
INFO:[31]: Certifying 'u1t1616ol_lamp.fits' 
INFO:[32]: Certifying 'u1t1616pl_disp.fits' 
INFO:[33]: Certifying 'u1t1616ql_wcp.fits' 
INFO:[34]: Certifying 'u381724gl_bpix.fits' 
INFO:[35]: Certifying 'u4d1930tl_1dx.fits' 
INFO:[36]: Certifying 'u6s1320ql_disp.fits' 
INFO:[37]: Certifying 'u6s1320rl_lamp.fits' 
INFO:[38]: Certifying 'u7d20378l_tds.fits' 
ERROR[4]: Validation failed for '/grp/hst/cdbs/lref/u7d20378l_tds.fits' : [Errno 2] No such file or directory: '/Users/jmiller/work/normal/lib/python2.7/site-packages/crds/hst/cdbs/cdbs_tpns/cos_tds.tpn' 
INFO:[39]: Certifying 'u8k1433nl_1dx.fits' 
ERROR[5]: Validation failed for '/grp/hst/cdbs/lref/u8k1433nl_1dx.fits' : Value for 'CENWAVE' of 1280 is not one of [1291, 1300, 1309, 1318, 1327, 1577, 1589, 1600, 1611, 1623, 1105, 1230, 1786, 1817, 1835, 1850, 1864, 1882, 1890, 1900, 1913, 1921, 1941, 1953, 1971, 1986, 2010, 2186, 2217, 2233, 2250, 2268, 2283, 2306, 2325, 2339, 2357, 2373, 2390, 2410, 2617, 2637, 2657, 2676, 2695, 2709, 2719, 2739, 2850, 2952, 2979, 2996, 3018, 3035, 3057, 3074, 3094, 2635, 2950, 3000, 3360] 
INFO:[40]: Certifying 'u8k1433ql_phot.fits' 
ERROR[6]: Validation failed for '/grp/hst/cdbs/lref/u8k1433ql_phot.fits' : Value for 'CENWAVE' of 1280 is not one of [1291, 1300, 1309, 1318, 1327, 1577, 1589, 1600, 1611, 1623, 1105, 1230, 1786, 1817, 1835, 1850, 1864, 1882, 1890, 1900, 1913, 1921, 1941, 1953, 1971, 1986, 2010, 2186, 2217, 2233, 2250, 2268, 2283, 2306, 2325, 2339, 2357, 2373, 2390, 2410, 2617, 2637, 2657, 2676, 2695, 2709, 2719, 2739, 2850, 2952, 2979, 2996, 3018, 3035, 3057, 3074, 3094, 2635, 2950, 3000, 3360] 
INFO:[41]: Certifying 'uas19356l_bpix.fits' 
INFO:[42]: Certifying 'ucl1623gl_pha.fits' 
INFO:[43]: Certifying 'v2e20129l_flat.fits' 
INFO:[44]: Certifying 'v3g18194l_disp.fits' 
ERROR[7]: Validation failed for '/grp/hst/cdbs/lref/v3g18194l_disp.fits' : Value for 'CENWAVE' of 1280 is not one of [1291, 1300, 1309, 1318, 1327, 1577, 1589, 1600, 1611, 1623, 1105, 1230, 1786, 1817, 1835, 1850, 1864, 1882, 1890, 1900, 1913, 1921, 1941, 1953, 1971, 1986, 2010, 2186, 2217, 2233, 2250, 2268, 2283, 2306, 2325, 2339, 2357, 2373, 2390, 2410, 2617, 2637, 2657, 2676, 2695, 2709, 2719, 2739, 2850, 2952, 2979, 2996, 3018, 3035, 3057, 3074, 3094, 2635, 2950, 3000, 3360] 
INFO:[45]: Certifying 'v3g18195l_lamp.fits' 
ERROR[8]: Validation failed for '/grp/hst/cdbs/lref/v3g18195l_lamp.fits' : Value for 'CENWAVE' of 1280 is not one of [1291, 1300, 1309, 1318, 1327, 1577, 1589, 1600, 1611, 1623, 1105, 1230, 1786, 1817, 1835, 1850, 1864, 1882, 1890, 1900, 1913, 1921, 1941, 1953, 1971, 1986, 2010, 2186, 2217, 2233, 2250, 2268, 2283, 2306, 2325, 2339, 2357, 2373, 2390, 2410, 2617, 2637, 2657, 2676, 2695, 2709, 2719, 2739, 2850, 2952, 2979, 2996, 3018, 3035, 3057, 3074, 3094, 2635, 2950, 3000, 3360] 
INFO:[46]: Certifying 'v3i16155l_tds.fits' 
ERROR[9]: Validation failed for '/grp/hst/cdbs/lref/v3i16155l_tds.fits' : [Errno 2] No such file or directory: '/Users/jmiller/work/normal/lib/python2.7/site-packages/crds/hst/cdbs/cdbs_tpns/cos_tds.tpn' 
INFO:[47]: Certifying 'v4s17227l_flat.fits' 
9 errors 
0 warnings 
47 infos 
 
